config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'welcome#index'

  resources :items

  resources :warehouses

  namespace :admin do
    resources :items, only: [:index]
    resources :item_warehouses, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  validates :name, presence: true
  validates :description, presence: true
  validates :unit_price, presence: true

  has_many :item_warehouses
  has_many :warehouses, through: :item_warehouses

  def self.search_by_name(search_params)
    where("LOWER(name) = ?", "#{search_params.downcase}")
  end
end

app/models/item_warehouse.rb
class ItemWarehouse < ApplicationRecord
  belongs_to :item
  belongs_to :warehouse
end

app/models/warehouse.rb
class Warehouse < ApplicationRecord
  validates :address, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :country, presence: true
  validates :postal_code, presence: true

  has_many :item_warehouses
  has_many :items, through: :item_warehouses

  def self.search_by_location(search_params)
    find_by_sql("SELECT * FROM warehouses WHERE LOWER(address) = '#{search_params.downcase}' OR LOWER(city) = '#{search_params.downcase}' OR LOWER(state) = '#{search_params.downcase}' OR LOWER(country) = '#{search_params.downcase}' OR LOWER(postal_code) = '#{search_params.downcase}'")
  end

  def item_quantity(item_id)
    ItemWarehouse.where(item_id: item_id, warehouse_id: self.id).first.quantity
  end
end

app/controllers/admin/item_warehouses_controller.rb
class Admin::ItemWarehousesController < ApplicationController
  def create
    if ItemWarehouse.where(search_params).empty?
      ItemWarehouse.create(item_id: params[:item_id], warehouse_id: params[:warehouse_id], quantity: params[:quantity].to_i)
    else
      iw = ItemWarehouse.where(search_params).first
      iw.update(quantity: params[:quantity].to_i + iw.quantity)
    end

    redirect_to "/warehouses/#{params[:warehouse_id]}"
  end

  private

  def search_params
    params.permit(:item_id, :warehouse_id)
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  def index
    @warehouse = Warehouse.find(params[:id])
    @items = Item.order("name ASC")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    if params[:search]
      @items = Item.search_by_name(params[:search])
    else
      @items = Item.order("name ASC")
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    @item.save

    if @item.save
      redirect_to "/items/#{@item.id}", alert: "#{@item.name} has been updated"
    else
      redirect_to "/items/#{@item.id}/edit"

      flash[:error] = @item.errors.full_messages
    end
  end

  def new
  end

  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to "/items/#{@item.id}"
    else
      redirect_to "/items/new"
      flash[:error] = @item.errors.full_messages
    end
  end

  def destroy
    ItemWarehouse.where(item_id: params[:id]).destroy_all
    Item.find(params[:id]).destroy

    redirect_to "/items"
  end

  private

  def item_params
    params.permit(:name, :description, :unit_price)
  end
end

app/controllers/warehouses_controller.rb
class WarehousesController < ApplicationController
  def index
    if params[:search]
      @warehouses = Warehouse.search_by_location(params[:search])
    else
      @warehouses = Warehouse.all
    end
  end

  def show
    @warehouse = Warehouse.find(params[:id])
  end

  def new
  end

  def create
    @warehouse = Warehouse.new(warehouse_params)

    if @warehouse.save
      redirect_to "/warehouses/#{@warehouse.id}"
    else
      redirect_to "/warehouses/new"

      flash[:error] = @warehouse.errors.full_messages
    end
  end

  def destroy
    ItemWarehouse.where(warehouse_id: params[:id]).destroy_all
    Warehouse.find(params[:id]).destroy

    redirect_to "/warehouses"
  end

  private

  def warehouse_params
    params.permit(:address, :city, :state, :country, :postal_code, :search)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admin/items/index.html.erb
<%= render "layouts/to_home" %>
<h1>Item Index</h1>
<br>
<ul>
  <% @items.each do |item| %>
    <div id=<%= item.id %>>
      <li><%= link_to item.name.capitalize, "/items/#{item.id}", method: :get, local: true%></li>

      <p><strong>Description: </strong><%= item.description %></p>

      <p><strong>Unit Price: </strong><%= number_to_currency(item.unit_price)%></p>

      <p><strong>Add Item to Inventory:</strong></p>
      <%= form_with url: "/admin/item_warehouses?item_id=#{item.id}&warehouse_id=#{@warehouse.id}", method: :post, local: true do |f| %>
        <%= f.label :quantity, "Quantity to Add:" %>
        <%= f.number_field :quantity, value: "1" %>
        <%= f.submit "Add to Warehouse at #{@warehouse.address}, #{@warehouse.city}, #{@warehouse.state}" %>
      <% end %>
    </div>
    <br>
  <% end %>
</ul>

app/views/items/edit.html.erb
<h1>Edit <%= @item.name%></h1>
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <strong><%= error %></strong>
    <br>
  <% end %>
<% end %>
<br>
<%= form_with url: "/items/#{@item.id}", method: :patch, local: true do |f| %>
  <strong><%= f.label :name, "Name:" %></strong>
  <%= f.text_field :name, style: 'text-transform: capitalize;', value: @item.name %>
  <br><br>

  <strong><%= f.label :description,"Description:" %></strong>
  <%= f.text_field :description, value: @item.description %>
  <br><br>

  <strong><%= f.label :unit_price, "Unit Price: $" %></strong>
  <%= f.number_field :unit_price, value: @item.unit_price %>

  <%= f.submit "Update Item" %>
<% end %>

app/views/items/index.html.erb
<%= render "layouts/to_home" %>
<h1>Item Index</h1>

<%= button_to "Create New Item", "/items/new", method: :get, local: true%>
<br>
<%= form_with url: items_path, method: :get, local: true do |f|%>
  <%= f.label :search, "Search By Item Name" %>
  <%= text_field_tag(:search, params[:search])  %>
  <%= f.submit "Search" %>
<% end %>

<ul>
  <% if @items.empty? %>
    <p>No Items in Iventory</p>
  <% else %>
    <% @items.each do |item| %>
    <div id=<%= item.id %>>
      <li><strong><%= link_to item.name.capitalize, "/items/#{item.id}", method: :get, local: true%></strong> <-- See Item Show Page</li>

      <p><strong>Description: </strong><%= item.description %></p>

      <p><strong>Unit Price: </strong><%= number_to_currency(item.unit_price)%></p>
    </div>
    <% end %>
  <% end %>
</ul>

app/views/items/new.html.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <strong><%= error %></strong>
    <br>
  <% end %>
<% end %>
<br>
<%= form_with url: "/items", method: :post, local: true do |f| %>
  <%= f.label :name, "Name: " %>
  <%= f.text_field :name %>
  <%= f.label :description, "Description: " %>
  <%= f.text_field :description %>
  <%= f.label :unit_price, "Unit Price: $" %>
  <%= f.number_field :unit_price %>

  <%= f.submit "Create Item" %>
<% end %>

app/views/items/show.html.erb
<%= render "layouts/to_home" %>
<br>
<%= render "layouts/to_item_index" %>

<h2><%= @item.name.capitalize %></h2>
<p><strong>Description: </strong><%= @item.description %></p>
<p><strong>Unit Price: </strong><%= number_to_currency(@item.unit_price) %></p>

<%= button_to "Edit Item", "/items/#{@item.id}/edit", method: :get, local: true %>
<br>
<%= button_to "Delete Item", "/items/#{@item.id}", method: :delete, local: true %>

app/views/layouts/_to_home.html.erb
<%= link_to "Home Page", root_path, method: :get, local: true %>

app/views/layouts/_to_item_index.html.erb
<%= link_to "All Items", "/items", method: :get, local: true %>

app/views/layouts/_to_warehouse_index.html.erb
<%= link_to "All Warehouses", "/warehouses", method: :get, local: true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShopifyTechnicalChallenge</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/warehouses/index.html.erb
<%= render "layouts/to_home" %>
<br>
<h1>Warehouses</h1>

<%= button_to "Create New Warehouse", "/warehouses/new", method: :get, local: true%>
<br>
<%= form_with url: warehouses_path, method: :get, local: true do |f|%>
  <%= f.label :search, "Search By Location" %>
  <%= text_field_tag(:search, params[:search])  %>
  <%= f.submit "Search" %>
<% end %>

<ul>
  <% @warehouses.each do |warehouse| %>
    <div id=<%= warehouse.id %>>
      <li><strong>Address: </strong><%= warehouse.address %></li>

      <p><strong>City: </strong><%= warehouse.city %></p>

      <p><strong>State: </strong><%= warehouse.state %></p>

      <p><strong>Country: </strong><%= warehouse.country %></p>

      <p><strong>Postal Code: </strong><%= warehouse.postal_code %></p>

      <%= button_to "View This Warehouse", "/warehouses/#{warehouse.id}", method: :get, local: true %>
      <br>
    </div>
  <% end %>
</ul>

app/views/warehouses/new.html.erb
<% if flash[:error] %>
  <% flash[:error].each do |error| %>
    <strong><%= error %></strong>
    <br>
  <% end %>
<% end %>

<%= form_with url: "/warehouses", method: :post, local: true do |f| %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :city %>
  <%= f.text_field :city %>
  <%= f.label :state %>
  <%= f.text_field :state %>
  <%= f.label :country %>
  <%= f.text_field :country %>
  <%= f.label :postal_code %>
  <%= f.number_field :postal_code %>

  <%= f.submit "Create Warehouse" %>
<% end %>

app/views/warehouses/show.html.erb
<%= render "layouts/to_home" %>
<br>
<%= render "layouts/to_warehouse_index" %>

<h1>Warehouse At: <%= @warehouse.address %>, <%= @warehouse.city %>, <%= @warehouse.state %> <%= @warehouse.postal_code %>, <%= @warehouse.country %> </h1>
<br>

<h2>Item Inventory: </h2>
<% if !@warehouse.items.empty? %>
  <div class="wh_items">
    <ul>
      <% @warehouse.items.distinct.each do |item| %>
        <div id=<%= item.id %>>
          <li><strong>Item Name: </strong><%= link_to item.name.capitalize, "/items/#{item.id}", method: :get, local: true%></li>

          <p><strong>Description: </strong><%= item.description %></p>

          <p><strong>Unit Price: </strong><%= number_to_currency(item.unit_price)%></p>

          <p><strong>Quantity in Stock: </strong><%= @warehouse.item_quantity(item.id) %></p>
        </div>
      <% end %>
    </ul>
  </div>
  <br>
<% else %>
  <p>No Items Currently in Inventory</p>
<% end %>

<%= link_to "Add Items to Warehouse Inventory", "/admin/items?id=#{@warehouse.id}", method: :get, local: true %>
<br>
<br>
<%= button_to "Delete Warehouse", "/warehouses/#{@warehouse.id}", method: :delete, local: true %>

app/views/welcome/index.html.erb
<h1>Welcome!</h1>

<h2>Find Warehouses and Items below:</h2>

<%= button_to "Warehouses", "/warehouses", method: :get, local: true %>
<br>
<%= button_to "Items", "/items", method: :get, local: true %>